---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: installing required libs
      apt:
        pkg: "{{ item }}"
        state: present
      with_items:
        - net-tools
        - netcat

- name: Environment
  hosts: consul
  roles:
    - consul
